<?php
/**
 * Template with placement of embeded video players into standard picture gallery
 *
 * @package     Keyup_ProductVideos
 * @author      Jan Kuchař <jan.kuchar@keyup.eu>
 * @copyright   Copyright (c) 2015 Keyup IT Services (http://www.keyup.eu)
 * @license     http://keyup.mit-license.org/2012 MIT License
 */
?>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $PVMC = Mage::getModel('keyup_productvideos/config');
    $PVH = Mage::helper('keyup_productvideos');
?>
<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<p class="product-image product-image-zoom">
    <?php
        $_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->escapeHtml($this->getImageLabel()).'" title="'.$this->escapeHtml($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</p>
<p class="zoom-notice" id="track_hint"><?php echo $this->__('Double click on above image to view full picture') ?></p>
<div class="zoom">
    <img id="zoom_out" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_out.gif') ?>" alt="<?php echo $this->__('Zoom Out') ?>" title="<?php echo $this->__('Zoom Out') ?>" class="btn-zoom-out" />
    <div id="track">
        <div id="handle"></div>
    </div>
    <img id="zoom_in" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_in.gif') ?>" alt="<?php echo $this->__('Zoom In') ?>" title="<?php echo $this->__('Zoom In') ?>" class="btn-zoom-in" />
</div>
<script type="text/javascript">
//<![CDATA[
    Event.observe(window, 'load', function() {
        product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out', 'track_hint');
    });
//]]>
</script>
<?php else: ?>
<p class="product-image">
<div class="productvideos-gallery <?php echo ($PVMC->isBehaviorMoviesFirst())?'productvideos-hidden':'';?>">
        <?php
            $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(265).'" alt="'.$this->escapeHtml($this->getImageLabel()).'" title="'.$this->escapeHtml($this->getImageLabel()).'" />';
            echo $_helper->productAttribute($_product, $_img, 'image');
        ?>
    </div>
    <?php
    if (!$PVMC->isBehaviorMoviesUnderDescription()) {
        $i=0;
        foreach ($PVH->buildEmbeds($_product) as $embed) {
            ?><div class="productvideos-player productvideos-player-<?php echo $i++;?>  <?php echo ($PVMC->isBehaviorPicturesFirst() || ($PVMC->isBehaviorMoviesFirst() && $i>1))?'productvideos-hidden':'';?>"><?php
            echo $embed;
            ?></div><?php
        }
    }
    ?>
</p>
<?php endif; ?>
<?php if (count($this->getGalleryImages()) > 0 || $PVH->getCount($_product) > 0): ?>
<div class="more-views">
    <h2><?php echo $this->__('More Views') ?></h2>
    <ul>
    <?php
    $i=0;
    foreach ($this->getGalleryImages() as $_image)
        if (!(($filterClass = $this->getGalleryFilterHelper()) && ($filterMethod = $this->getGalleryFilterMethod()) && !Mage::helper($filterClass)->$filterMethod($_product, $_image))) {
        $_images .= <<<IMG
        <li>
            <a href="#" onclick="popWin('{$this->getGalleryUrl($_image)}', 'gallery', 'width=300,height=300,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;" title="{$this->escapeHtml($_image->getLabel())}">
                <img src="{$this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(56)}" width="56" height="56" alt="{$this->escapeHtml($_image->getLabel())}" />
            </a>
        </li>
IMG;
        $i++;
    }
    if (!$PVMC->isBehaviorMoviesUnderDescription()) {
        $i=0;
        foreach ($PVH->buildThumbs($_product) as $thumb) {
            $_videos .= <<<VID
            <li>
                <a class="thumb-link-pv" href="#" data-video-index="$i">
                    <img src="{$thumb}" width="75" height="75" alt="{$thumb}" />
                </a>
            </li>
VID;
            $i++;
        }
    }
    echo ($PVMC->isBehaviorMoviesFirst()) ? $_videos.$_images : $_images.$_videos;
    ?>
    </ul>
</div>
<?php endif; ?>
